version: 2

jobs:
  build:
    docker:
      - image: aturkewi/curriculum-solution-parser
    steps:
      - checkout
      - run: echo "we can run a cirlce command"
      - run:
          name: Update master
          command: |
            if [[ "$CIRCLE_BRANCH" = "solution" ]]; then
              parser.rb
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
