version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run: echo "we can run a cirlce command"
  test:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run: echo "we are running a test!!!"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
