version: 2

jobs:
  build:
    docker:
      - image: aturkewi/curriculum-solution-parser
    steps:
      - checkout
      - run: echo "we can run a cirlce command"
      - run: parser.rb

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      filters:
            branches:
              only:
                - solution
